spring.application.name=attendance-backend

# ===== ភ្ជាប់ទៅកាន់ PostgreSQL Database =====
# កន្លែងនេះវានឹងដកស្រង់តម្លៃពី Render Environment Variable បើអត់មានវាទើបរត់ទៅ localhost ក្នុងម៉ាស៊ីនបង
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== Hibernate & JPA Settings =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== Server Port =====
server.port=8080

# ===== Mail Configuration (សម្រាប់ផ្ញើ OTP) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=465
# លាក់ព័ត៌មានអ៊ីមែល និងលេខសម្ងាត់ App Password ជាមួយ Environment Variable
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
